{
 "title": "[MAGNET-CDP] Workload Monitor",
 "description": "MAGNET-CDP",
 "tags": [ "YOUR-DASHBOARD" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "label", "query": "martech-project" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{label_node6=~\"$label\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "magnet-cdp-dev, magnet-cdp-sit, magnet-cdp-uat, magnet-cdp-stg"
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "pod_down",
    "query": {
     "query": "label_values(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU Usage/Quota",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\"})/sum(kube_pod_container_resource_limits{unit=\"core\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "% CPU usage/Request",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\"})/sum(kube_pod_container_resource_requests{unit=\"core\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "% Memory Usage/Request",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\"})/sum(kube_pod_container_resource_requests{unit=\"byte\"})"
      }
     ]
    },
    {
     "title": "% Disk Usage/Quota",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
      }
     ]
    },
    {
     "title": "% Memory Usage/Quota",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\"})/sum(kube_pod_container_resource_limits{unit=\"byte\"})"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) / sum(kube_node_labels{})"
      }
     ]
    },
    {
     "title": "Pod Not Ready count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"}==1)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM USAGE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", node=~\"$node\", pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory Trending",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE TREND by %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pod:container_cpu_usage:sum{namespace=~\"$namespace\", pod=~\"$deployment.*\", pod=~\"$deployment_config.*\"}) by (pod) / sum(kube_pod_container_resource_limits{unit=\"core\",namespace=~\"$namespace\", pod=~\"$deployment.*\", pod=~\"$deployment_config.*\"}) by (pod) * 100",
       "legendFormat": "{{pod}}"
      },
      { "expr": "100", "legendFormat": "100" }
     ]
    },
    {
     "title": "MEM USAGE TREND by %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$deployment.*\", pod=~\"$deployment_config.*\"}) by (pod) / sum(kube_pod_container_resource_limits{unit=\"byte\",namespace=~\"$namespace\", pod=~\"$deployment.*\", pod=~\"$deployment_config.*\"}) by (pod) * 100",
       "legendFormat": "{{pod}}"
      },
      { "expr": "100", "legendFormat": "100" }
     ]
    }
   ]
  },
  {
   "title": "Ingress 5m",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(haproxy_backend_connections_total{exported_namespace=~\"$namespace\",route=~\"$deployment.*\", pod=~\"router-external.*\"}[5m])) by (route)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "5xx Response",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(haproxy_server_http_responses_total{code=\"5xx\", exported_namespace=~\"$namespace\", route=~\"$deployment.*\"}[15m])) by (route)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4xx Response",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(haproxy_server_http_responses_total{code=\"4xx\", exported_namespace=~\"$namespace\", route=~\"$deployment.*\"}[15m])) by (route)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\",pod=~\"$deployment.*\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod=~\"$deployment.*\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshoot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current pods with Not Ready",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node with pod Not Ready",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod_down\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory Current Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment RESOURCE USAGE LIMIT",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{unit=\"byte\",namespace=~\"$namespace\",pod=~\"$pod.*\"}, \"deployment\",\"$1\",\"pod\", \"(.+)-.*-.*\")) by (deployment)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{unit=\"core\",namespace=~\"$namespace\",pod=~\"$pod.*\"}, \"deployment\",\"$1\",\"pod\", \"(.+)-.*-.*\")) by (deployment)"
      }
     ]
    },
    {
     "title": "POD RESOURCE USAGE CURRENT",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\",namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{unit=\"byte\",namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(pod:container_cpu_usage:sum{namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"core\",namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(pod:container_cpu_usage:sum{namespace=~\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{unit=\"core\",namespace=~\"$namespace\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}